name: spacex
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^8.0.5
  easy_localization: ^3.0.2
  http: ^1.0.0
  build_runner: ^2.4.5
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  logger: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.0
  
flutter:
  uses-material-design: true

  assets:
    - assets/translations/


